name: multi_modular_clean_arch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

workspace:
  - core/data
  - core/domain
  - core/presentation
  - features/settings/app_settings
  - features/settings/profile
  - features/home/main
  - features/auth/register
  - features/auth/login
  - features/movies

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  melos: ^8.7.0

melos:
  scripts:
    reset:
      run: melos clean && melos bootstrap
    update-deps:
      run: melos exec -- flutter pub upgrade
    test:
      run: melos exec -- flutter test  
        

